### ISSUE TITLE
工程无法运行

### ISSUE THREAD

**Issue by chrispualliu** [junpengxu/Apollo#3]
Dear junpeng: 
1）ubuntu18.04下载后解压;
2）cd ~/Apollo-main
3)  sudo npm install            ----报错：ENOENT: no such file or directory.........package.json (但是生成了package-lock.json文件)
4）npm run dev                 -----报错:  npm ERR! ENOENT .......（等等）

请教下，是不是哪里配置不对？我运行PanjiaChen的vue-element-admin-master这个工程没有问题。

**Comment by chrispualliu** [comment]
如果方便，可以加我微信（15084747014），nice to meet u.

**Comment by junpengxu** [comment]
你好， 首先很感谢你的关注，关于你的问题，我这几天尝试复现一下，有进展会同步给你。再次感谢你对项目的关注。

**Comment by junpengxu** [comment]
你尝试进入client目录中执行npm install，npm run dev。应该是不需要sudo的

**Comment by CattleHome** [comment]
开始注册，注册失败

**Comment by CattleHome** [comment]
你这个要自己创建数据表的吗？

**Comment by CattleHome** [comment]
后台的账号密码是什么呢？

**Comment by junpengxu** [comment]
> 这个需要先自己调用接口去创建的，你如果是在本地部署的话， 是没有账户的。 
> 参考 https://github.com/junpengxu/Apollo/blob/main/server/app/views/user.py#L15
