### ISSUE TITLE
项目的账号密码

### ISSUE THREAD

**Issue by CattleHome** [junpengxu/Apollo#4]
项目的账号密码是什么呢？

**Comment by junpengxu** [comment]
这个需要先自己调用接口去创建的，你如果是在本地部署的话， 是没有账户的。
参考 https://github.com/junpengxu/Apollo/blob/main/server/app/views/user.py#L15

**Comment by CattleHome** [comment]
好的，我看看，谢谢博主



---原始邮件---
发件人: "Xu ***@***.***&gt;
发送时间: 2022年3月14日(周一) 下午5:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [junpengxu/Apollo] 项目的账号密码 (Issue #4)




 
这个需要先自己调用接口去创建的，你如果是在本地部署的话， 是没有账户的。
 参考 https://github.com/junpengxu/Apollo/blob/main/server/app/views/user.py#L15
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CattleHome** [comment]
本地的话没有账号那怎么登陆呢？

**Comment by CattleHome** [comment]
我项目已经启动了，但是要登陆账号密码才能进去
![image](https://user-images.githubusercontent.com/42318566/158293111-e8da1bfe-5ba5-4eb8-bde2-c00515f5b57c.png)

**Comment by junpengxu** [comment]
把后端服务正常启动，然后把数据库给生成好， 用curl或者postman 直接去调用用户创建的api创建一个用户账户。

**Comment by wendy0075** [comment]
有sql表可以发一个吗
